spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: finance-manager

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev,test

  kafka:
    bootstrap-servers: localhost:29092
    group-id: email-sender-group
    topics:
      welcome-email:
        name: welcome-email_topic
        num-partitions: 3
        replication-factor: 1
    producer:
      retries: 3
      request-timeout-ms: 5000
      max-block-ms: 5000

server:
  port: 8086

application:
  security:
    frontend-allow-url: ${FRONTEND_ALLOW_URL}
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 900000 # 15 min
      cookie-name: jwt-cookie
      refresh-token:
        expiration: 1296000000 # 15 days
        cookie-name: refresh-jwt-cookie

logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace