### authrorization
GET http://localhost:8086/api/v1/admin/resource
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1haWwuY29tIiwiaWF0IjoxNzQ0OTgwNTQ2LCJleHAiOjE3NDQ5ODE0NDZ9.H8iCGK9hZaYxHBI1wDz7JaL6BgApSSha855cJe5L4zs
