package com.voedev.financebackend.model.enums;

public enum Privilege {

    READ_PRIVILEGE, WRITE_PRIVILEGE, UPDATE_PRIVILEGE, DELETE_PRIVILEGE,

    ADMIN_READ_PRIVILEGE, ADMIN_WRITE_PRIVILEGE, ADMIN_UPDATE_PRIVILEGE, ADMIN_DELETE_PRIVILEGE
}
