spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-sender

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: email-sender-group

server:
  port: 8087

logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace