spring:
  mail:
    default-encoding: UTF-8
  config:
    import: optional:file:.env[.properties]
  application:
    name: notification-sender

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer: # KafkaListener
      group-id: email-sender-group
    group-id: # KafkaProperties
      email-sender-group
    topics:
      welcome-email:
        name: welcome-email_topic
        num-partitions: 3
        replication-factor: 1

mailjet:
  smtp:
    host: ${MAILJET_HOST}
    port: ${MAILJET_PORT}
    username: ${MAILJET_API_KEY_PUBLIC}
    password: ${MAILJET_API_KEY_PRIVATE}

server:
  port: 8087

logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
